# Generated by Django 6.0.2 on 2026-02-24 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_alter_booking_room_and_more'),
        ('hotels', '0002_room'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HotelRoom',
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['price_per_night'], name='hotels_room_price_p_ddffaf_idx'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['created_at'], name='hotels_room_created_421313_idx'),
        ),
    ]
