# Generated by Django 6.0.2 on 2026-02-24 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_alter_booking_options_booking_created_at_and_more'),
        ('hotels', '0002_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='hotels.room', verbose_name='Номер отеля'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['room', 'date_start'], name='bookings_bo_room_id_a89715_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['date_start', 'date_end'], name='bookings_bo_date_st_a6eb0b_idx'),
        ),
    ]
